Repository rcbops/pytest-rpc, pull requests merged in 2018-08, with the labels that each got.

#48 MAINT add collection of MOLECULE_GIT_COMMIT
  pytest_rpc/__init__.py
Labels: v0.11.0

#49 MAINT - Fix data gather get_resource_list_by_name
  pytest_rpc/helpers.py
  tests/helpers/test_get_resource_list_by_name.py
Labels: bug, v0.11.0

#50 ASC-856 Update get_osa_version helper
  pytest_rpc/helpers.py
  tests/helpers/test_get_osa_version.py
Labels: v0.12.0

#52 MAINT - Fix Formatting in Helper Tests
  tests/helpers/test_delete_instance.py
  tests/helpers/test_delete_volume.py
  tests/helpers/test_get_expected_value.py
  tests/helpers/test_resource_in_list.py
Labels: v0.12.0

#51 ASC-871 Update helpers to address netwon
  pytest_rpc/helpers.py
  tests/helpers/test_create_floating_ip.py
  tests/helpers/test_create_instance.py
  tests/helpers/test_create_snapshot_from_instance.py
  tests/helpers/test_delete_instance.py
  tests/helpers/test_delete_it.py
  tests/helpers/test_delete_volume.py
  tests/helpers/test_get_id_by_name.py
  tests/helpers/test_stop_server_instance.py
Labels: v0.12.0
